+ `grant_type`: `password` (string) Grand Type
+ `client_id`: 2 (number) Client Id
+ `client_secret`: `o2p9sl4ZcCKBnHG3I6KUkMweX0fyzwyH4I3HWPbP` (string) Client Id
+ `username`: `admin@admin.com` (string) Username
+ `password`: `admin123@` (string) Password